/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

public enum PTEID_FileType {
  PTEID_FILETYPE_UNKNOWN = 0,
  PTEID_FILETYPE_TLV,
  PTEID_FILETYPE_XML,
  PTEID_FILETYPE_CSV
}

}
