/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

public enum PTEID_CertifType {

    /// <summary>UNKNOWN certificate</summary>
    PTEID_CERTIF_TYPE_UNKNOWN,

    /// <summary>RRN certificate</summary>
    PTEID_CERTIF_TYPE_RRN,

    /// <summary>Root certificate</summary>
    PTEID_CERTIF_TYPE_ROOT,

    /// <summary>CA certificate</summary>
    PTEID_CERTIF_TYPE_CA,

    /// <summary>Authentication certificate</summary>
    PTEID_CERTIF_TYPE_AUTHENTICATION,

    /// <summary>Signature certificate</summary>
    PTEID_CERTIF_TYPE_SIGNATURE
}

}
