/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

using System;
using System.Runtime.InteropServices;

/// <summary>
/// Exception class No Card Present (error code = EIDMW_ERR_NO_CARD).
/// Throw when no card is present.
/// Used in : 
/// - PTEID_ReaderContext::getCardType() 
/// - PTEID_ReaderContext::getCard() 
/// - PTEID_ReaderContext::getEIDCard() 
/// - PTEID_ReaderContext::getKidsCard() 
/// - PTEID_ReaderContext::getForeignerCard()
/// - PTEID_ReaderContext::getSISCard()
/// </summary>
public class PTEID_ExNoCardPresent : PTEID_Exception {
  private HandleRef swigCPtr;

  internal PTEID_ExNoCardPresent(IntPtr cPtr, bool cMemoryOwn) : base(pteidlib_dotNetPINVOKE.PTEID_ExNoCardPresentUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PTEID_ExNoCardPresent obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PTEID_ExNoCardPresent() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pteidlib_dotNetPINVOKE.delete_PTEID_ExNoCardPresent(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PTEID_ExNoCardPresent() : this(pteidlib_dotNetPINVOKE.new_PTEID_ExNoCardPresent(), true) {
  }

}

}
