// Constants.js
.pragma library

// Screen Size
var SCREEN_MINIMUM_WIDTH = 1024
var SCREEN_MINIMUM_HEIGHT = 576;

// Views Relative Size
var MAIN_MENU_VIEW_RELATIVE_SIZE = 0.25
var SUB_MENU_VIEW_RELATIVE_SIZE = 0.25
var CONTENT_PAGES_VIEW_RELATIVE_SIZE = 0.50

// Main Menu Relative Size
var IMAGE_LOGO_RELATIVE_H_SIZE = 0.80
var IMAGE_LOGO_RELATIVE_V_POS = 0.05
var MAIN_MENU_RELATIVE_V_SIZE = 0.40
var RECT_HELP_DIFINITIONS_RELATIVE_V_POS = 0.10

// Sub Menu Relative Size
var SUB_MENU_RELATIVE_H_SIZE = 0.80
var SUB_MENU_RELATIVE_V_ITEM_SIZE = 0.15
var SUB_MENU_RELATIVE_LINE_H_SIZE = 0.005

// Content Pages Relative Size
var PAGE_RELATIVE_H_SIZE = 0.95
var PAGE_RELATIVE_V_SIZE = 0.95

// Home Page Relative Size
var HOME_PAGE_RELATIVE_H_SIZE = 0.8
var HOME_PAGE_RELATIVE_V_SIZE = 0.55

// Text Size
var SIZE_TEXT_MAIN_MENU = 16
var SIZE_TEXT_SUB_MENU = 16
var SIZE_TEXT_TITLE = 20
var SIZE_TEXT_LABEL = 12
var SIZE_TEXT_FIELD = 12
var SIZE_TEXT_BODY = 16

// Defined Colors
var COLOR_MAIN_BLUE = "#3C5DBC"
var COLOR_MAIN_PRETO = "#333333"
var COLOR_MAIN_SOFT_GRAY = "#EDEDED"
var COLOR_MAIN_DARK_GRAY = "#9FAFDF"

// Menus Text Colors
var COLOR_TEXT_MAIN_MENU_SELECTED = COLOR_MAIN_SOFT_GRAY
var COLOR_TEXT_MAIN_MENU_DEFAULT = COLOR_MAIN_DARK_GRAY
var COLOR_TEXT_SUB_MENU_SELECTED = COLOR_MAIN_SOFT_GRAY
var COLOR_TEXT_SUB_MENU_DEFAULT = COLOR_MAIN_PRETO
var COLOR_TEXT_SUB_MENU_MOUSE_OVER = COLOR_MAIN_BLUE
var COLOR_TEXT_TITLE = COLOR_MAIN_BLUE

// Colors
var COLOR_BACKGROUND_MAIN_MENU = COLOR_MAIN_BLUE
var COLOR_BACKGROUND_SUB_MENU = COLOR_MAIN_BLUE
var COLOR_LINE_SUB_MENU = COLOR_MAIN_SOFT_GRAY
var COLOR_TEXT_BODY = COLOR_MAIN_PRETO
var COLOR_TEXT_LABEL = COLOR_MAIN_BLUE
var COLOR_TEXT_FIELD_TEXT = COLOR_MAIN_BLUE
var COLOR_ITEM_BULLETED = COLOR_MAIN_BLUE

// Forms
var COLOR_FORM_GLOW = COLOR_MAIN_SOFT_GRAY
var FORM_GROW_RADIUS = 5
var FORM_GLOW_CORNER_RADIUS = 5
var FORM_GLOW_SPREAD = 0
var SIZE_FORM_RECT_TOP_V_RELATIVE = 0.10
var SIZE_FORM_RECT_NAME_RELATIVE = 0.7
var SIZE_FORM_RECT_NAME_V_RELATIVE = 0.2
var SIZE_FORM_RECT_PHOTO_RELATIVE = 0.3
var SIZE_FORM_TEXT_RELATIVE = 0.9
var SIZE_ROW_SPACE = 20

// Animation time
var ANIMATION_STATE_TO_HOME = 200
var ANIMATION_STATE_TO_NORMAL = 200
var ANIMATION_STATE_OPACITY_TO_HOME = 100
var ANIMATION_STATE_OPACITY_TO_NORMAL = 100
