/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

using System;
using System.Runtime.InteropServices;

public class PTEID_EId : PTEID_XMLDoc {
  private HandleRef swigCPtr;

  internal PTEID_EId(IntPtr cPtr, bool cMemoryOwn) : base(pteidlib_dotNetPINVOKE.PTEID_EIdUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PTEID_EId obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PTEID_EId() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pteidlib_dotNetPINVOKE.delete_PTEID_EId(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public string getDocumentVersion() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDocumentVersion(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDocumentType() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDocumentType(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getFirstName1() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getFirstName1(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSurname() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSurname(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getGender() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getGender(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDateOfBirth() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDateOfBirth(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getLocationOfBirth() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getLocationOfBirth(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getNobility() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getNobility(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getNationality() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getNationality(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getNationalNumber() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getNationalNumber(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDuplicata() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDuplicata(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSpecialOrganization() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSpecialOrganization(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getMemberOfFamily() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getMemberOfFamily(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getLogicalNumber() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getLogicalNumber(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getChipNumber() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getChipNumber(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getValidityBeginDate() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getValidityBeginDate(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getValidityEndDate() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getValidityEndDate(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getIssuingMunicipality() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getIssuingMunicipality(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getAddressVersion() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getAddressVersion(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getStreet() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getStreet(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getZipCode() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getZipCode(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getMunicipality() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getMunicipality(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getCountry() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getCountry(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSpecialStatus() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSpecialStatus(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getHeight() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getHeight(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDocumentNumber() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDocumentNumber(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getTaxNo() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getTaxNo(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSocialSecurityNo() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSocialSecurityNo(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getHealthNo() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getHealthNo(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getIssuingEntity() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getIssuingEntity(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getGivenNameFather() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getGivenNameFather(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSurnameFather() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSurnameFather(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getGivenNameMother() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getGivenNameMother(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSurnameMother() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSurnameMother(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getPhoto() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getPhoto(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDistrict() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDistrict(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getStreetName() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getStreetName(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getCivilParish() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getCivilParish(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getStreetType1() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getStreetType1(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getStreetType2() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getStreetType2(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getBuildingType1() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getBuildingType1(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getBuildingType2() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getBuildingType2(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getDoorNo() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getDoorNo(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getFloor() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getFloor(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getSide() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getSide(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getLocality() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getLocality(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getZip4() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getZip4(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getZip3() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getZip3(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getPostalLocality() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getPostalLocality(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getPersoData() {
    string ret = pteidlib_dotNetPINVOKE.PTEID_EId_getPersoData(swigCPtr);
    if (pteidlib_dotNetPINVOKE.SWIGPendingException.Pending) throw pteidlib_dotNetPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
