######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 21 11:11:18 2007
######################################################################


include(../_Builds/eidcommon.mak)

TEMPLATE = app
TARGET = crl_unit_test.out
VERSION = $${APPLAYERLIB_MAJ}.$${APPLAYERLIB_MIN}.$${APPLAYERLIB_REV}

message("Compile $$TARGET")

###
### Installation setup
###
target.path = $${INSTALL_DIR_LIB}
INSTALLS += target

QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64"


###
### Compiler setup
###

CONFIG -= warn_on
CONFIG -= qt
CONFIG += link_pkgconfig

## destination directory for the compiler
DESTDIR = .
DEFINED += APPLAYER_EXPORTS

#external libs are openjp2="libopenjp2-7-dev", png="libpng-dev", z="zlib1g-dev"
LIBS += -L../lib \
	    -l$${COMMONLIB} \
	    -lcrypto -lssl \
	    -lxerces-c \
	    -lxml-security-c \
	    -lcurl \
	    -lpng \
	    -lz \
	    -lzip

macx:  LIBS += -lopenjp2
!macx: PKGCONFIG += libopenjp2


!macx: LIBS += -Wl,-R,'../lib'
LIBS += ../lib/libpteid-poppler.a
!macx: LIBS += -Wl,--exclude-libs,ALL 

macx: LIBS += -L $$DEPS_DIR/openssl-3/lib/ \
	-L$$DEPS_DIR/xerces-c-3.2.4/lib/ \
	-L$$DEPS_DIR/libzip/lib/ \
	-L$$DEPS_DIR/libpng/lib \
	-L$$DEPS_DIR/openjpeg/lib \
	-L$$DEPS_DIR/xml-security-c/lib \
	-L$$DEPS_DIR/libcurl/lib/
macx: LIBS += -Wl,-framework -Wl,CoreFoundation
macx: LIBS += -Wl,-framework -Wl,SystemConfiguration
macx: LIBS += -Wl,-framework -Wl,CoreServices
macx: LIBS += -liconv
macx: INCLUDEPATH +=$$DEPS_DIR/openssl-3/include $$DEPS_DIR/libzip/include $$DEPS_DIR/openjpeg/include/openjpeg-2.4/ $$DEPS_DIR/xml-security-c/include/ $$DEPS_DIR/xerces-c-3.2.4/include $$DEPS_DIR/libpng/include
macx: INCLUDEPATH += /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CFNetwork.framework/Headers/
!macx: INCLUDEPATH += /usr/include/libpng16

LIBS += -l$${CARDLAYERLIB}
LIBS += -lz

DEPENDPATH += .
INCLUDEPATH += . ../common ../pteid-poppler ../cardlayer ../eidlib ../dialogs
macx: INCLUDEPATH += /usr/local/include
INCLUDEPATH += $${PCSC_INCLUDE_DIR}

DEFINES += APPLAYER_EXPORTS OPENSSL_SUPPRESS_DEPRECATED
# Input
HEADERS += \
	../applayer/APLCardFile.h \
	../applayer/APLCard.h \
	../applayer/APLCertif.h \
	../applayer/APLCrypto.h \
	../applayer/APLReader.h \
	../applayer/APLConfig.h \
	../applayer/APLCCXmlDoc.h \
	../applayer/CardFile.h \
	../applayer/CertStatusCache.h \
	../applayer/cryptoFramework.h \
	../applayer/MiscUtil.h \
	../applayer/XercesUtils.h \
	../applayer/CardPteid.h	    \
	../applayer/CardPteidDef.h   \
	../applayer/cryptoFwkPteid.h \
	../applayer/APLCardPteid.h   \
	../applayer/PhotoPteid.h \
	../applayer/SecurityContext.h  \
	../applayer/APLPublicKey.h \
	../applayer/SigContainer.h \
	../applayer/XadesSignature.h \
	../applayer/TSAClient.h \
	../applayer/SODParser.h \ 
	../applayer/cJSON.h \
	../applayer/SSLConnection.h \
	../applayer/PNGConverter.h \
	../applayer/PAdESExtender.h \
	../applayer/J2KHelper.h \
	../applayer/PDFSignature.h \
	../applayer/CurlUtil.h \
	../applayer/proxyinfo.h 

SOURCES += \
	../applayer/APLCertif.cpp        \
	../applayer/APLCrypto.cpp        \
	../applayer/APLCardPteid.cpp     \
	../applayer/APLConfig.cpp	\
	../applayer/APLReader.cpp        \
	../applayer/CardFile.cpp	        \
	../applayer/CardPteid.cpp        \
	../applayer/CertStatusCache.cpp  \
	../applayer/cryptoFramework.cpp  \
	../applayer/cryptoFwkPteid.cpp   \
	../applayer/APLCard.cpp          \ 
	../applayer/MiscUtil.cpp \
	../applayer/XercesUtils.cpp \
	../applayer/PhotoPteid.cpp \
	../applayer/APLPublicKey.cpp \
	../applayer/SigContainer.cpp \
	../applayer/XadesSignature.cpp \
	../applayer/RemoteAddress.cpp  \
	../applayer/RemoteAddressRequest.cpp \
	../applayer/SODParser.cpp \
	../applayer/SSLConnection.cpp \
	../applayer/TSAClient.cpp \
	../applayer/SecurityContext.cpp \
	../applayer/sign-pkcs7.cpp \
	../applayer/cJSON.c \
	../applayer/CRLFetcher.cpp \
	../applayer/PDFSignature.cpp \
	../applayer/PAdESExtender.cpp \
	../applayer/MutualAuthentication.cpp \
	../applayer/PNGConverter.cpp \
	../applayer/J2KHelper.cpp \
	../applayer/CurlUtil.cpp \
	../applayer/proxyinfo.cpp \
	main.cpp

# Disable annoying and mostly useless gcc warning and add hidden visibility for non-exposed classes and functions
QMAKE_CXXFLAGS += -Wno-write-strings -fvisibility=hidden
QMAKE_CFLAGS += -fvisibility=hidden
