/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

public class BEID_Address extends BEID_XMLDoc {
  private long swigCPtr;

  protected BEID_Address(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_AddressUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_Address obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_Address(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getMunicipality() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Address_getMunicipality(swigCPtr, this);
  }

  public String getDistrict() {
    return beidlibJava_WrapperJNI.BEID_Address_getDistrict(swigCPtr, this);
  }

  public String getStreetName() {
    return beidlibJava_WrapperJNI.BEID_Address_getStreetName(swigCPtr, this);
  }

  public String getCivilParish() {
    return beidlibJava_WrapperJNI.BEID_Address_getCivilParish(swigCPtr, this);
  }

  public String getStreetType1() {
    return beidlibJava_WrapperJNI.BEID_Address_getStreetType1(swigCPtr, this);
  }

  public String getStreetType2() {
    return beidlibJava_WrapperJNI.BEID_Address_getStreetType2(swigCPtr, this);
  }

  public String getBuildingType1() {
    return beidlibJava_WrapperJNI.BEID_Address_getBuildingType1(swigCPtr, this);
  }

  public String getBuildingType2() {
    return beidlibJava_WrapperJNI.BEID_Address_getBuildingType2(swigCPtr, this);
  }

  public String getDoorNo() {
    return beidlibJava_WrapperJNI.BEID_Address_getDoorNo(swigCPtr, this);
  }

  public String getFloor() {
    return beidlibJava_WrapperJNI.BEID_Address_getFloor(swigCPtr, this);
  }

  public String getSide() {
    return beidlibJava_WrapperJNI.BEID_Address_getSide(swigCPtr, this);
  }

  public String getLocality() {
    return beidlibJava_WrapperJNI.BEID_Address_getLocality(swigCPtr, this);
  }

  public String getPlace() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Address_getPlace(swigCPtr, this);
  }

  public String getZip4() {
    return beidlibJava_WrapperJNI.BEID_Address_getZip4(swigCPtr, this);
  }

  public String getZip3() {
    return beidlibJava_WrapperJNI.BEID_Address_getZip3(swigCPtr, this);
  }

  public String getPostalLocality() {
    return beidlibJava_WrapperJNI.BEID_Address_getPostalLocality(swigCPtr, this);
  }

}
