/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

public class BEID_Certificate extends BEID_Crypto {
  private long swigCPtr;

  protected BEID_Certificate(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_CertificateUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_Certificate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_Certificate(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getLabel() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getLabel(swigCPtr, this);
  }

  public long getID() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getID(swigCPtr, this);
  }

  public BEID_CertifStatus getStatus() throws BEID_Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_getStatus__SWIG_0(swigCPtr, this));
  }

  public BEID_CertifStatus getStatus(BEID_ValidationLevel crl, BEID_ValidationLevel ocsp) throws BEID_Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_getStatus__SWIG_1(swigCPtr, this, crl.swigValue(), ocsp.swigValue()));
  }

  public BEID_CertifType getType() throws BEID_Exception {
    return BEID_CertifType.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_getType(swigCPtr, this));
  }

  public BEID_ByteArray getCertData() throws BEID_Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_Certificate_getCertData(swigCPtr, this), false);
  }

  public void getFormattedData(BEID_ByteArray data) {
    beidlibJava_WrapperJNI.BEID_Certificate_getFormattedData(swigCPtr, this, BEID_ByteArray.getCPtr(data), data);
  }

  public String getSerialNumber() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getSerialNumber(swigCPtr, this);
  }

  public String getOwnerName() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getOwnerName(swigCPtr, this);
  }

  public String getIssuerName() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getIssuerName(swigCPtr, this);
  }

  public String getValidityBegin() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getValidityBegin(swigCPtr, this);
  }

  public String getValidityEnd() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getValidityEnd(swigCPtr, this);
  }

  public long getKeyLength() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_getKeyLength(swigCPtr, this);
  }

  public boolean isRoot() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_isRoot(swigCPtr, this);
  }

  public boolean isTest() {
    return beidlibJava_WrapperJNI.BEID_Certificate_isTest(swigCPtr, this);
  }

  public boolean isFromBeidValidChain() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_isFromBeidValidChain(swigCPtr, this);
  }

  public boolean isFromCard() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_isFromCard(swigCPtr, this);
  }

  public BEID_Certificate getIssuer() throws BEID_Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_Certificate_getIssuer(swigCPtr, this), false);
  }

  public long countChildren() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_Certificate_countChildren(swigCPtr, this);
  }

  public BEID_Certificate getChildren(long ulIndex) throws BEID_Exception {
    return new BEID_Certificate(beidlibJava_WrapperJNI.BEID_Certificate_getChildren(swigCPtr, this, ulIndex), false);
  }

  public BEID_Crl getCRL() throws BEID_Exception {
    return new BEID_Crl(beidlibJava_WrapperJNI.BEID_Certificate_getCRL(swigCPtr, this), false);
  }

  public BEID_OcspResponse getOcspResponse() throws BEID_Exception {
    return new BEID_OcspResponse(beidlibJava_WrapperJNI.BEID_Certificate_getOcspResponse(swigCPtr, this), false);
  }

  public BEID_CertifStatus verifyCRL(boolean forceDownload) throws BEID_Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_verifyCRL__SWIG_0(swigCPtr, this, forceDownload));
  }

  public BEID_CertifStatus verifyCRL() throws BEID_Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_verifyCRL__SWIG_1(swigCPtr, this));
  }

  public BEID_CertifStatus verifyOCSP() throws BEID_Exception {
    return BEID_CertifStatus.swigToEnum(beidlibJava_WrapperJNI.BEID_Certificate_verifyOCSP(swigCPtr, this));
  }

}
