/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.belgium.eid;

public class BEID_EId extends BEID_XMLDoc {
  private long swigCPtr;

  protected BEID_EId(long cPtr, boolean cMemoryOwn) {
    super(beidlibJava_WrapperJNI.SWIGBEID_EIdUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BEID_EId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      beidlibJava_WrapperJNI.delete_BEID_EId(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getDocumentVersion() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getDocumentVersion(swigCPtr, this);
  }

  public String getDocumentType() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getDocumentType(swigCPtr, this);
  }

  public String getCountry() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getCountry(swigCPtr, this);
  }

  public String getFirstName1() {
    return beidlibJava_WrapperJNI.BEID_EId_getFirstName1(swigCPtr, this);
  }

  public String getSurname() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getSurname(swigCPtr, this);
  }

  public String getGender() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getGender(swigCPtr, this);
  }

  public String getDateOfBirth() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getDateOfBirth(swigCPtr, this);
  }

  public String getLocationOfBirth() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getLocationOfBirth(swigCPtr, this);
  }

  public String getNobility() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getNobility(swigCPtr, this);
  }

  public String getNationality() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getNationality(swigCPtr, this);
  }

  public String getNationalNumber() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getNationalNumber(swigCPtr, this);
  }

  public String getDuplicata() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getDuplicata(swigCPtr, this);
  }

  public String getSpecialOrganization() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getSpecialOrganization(swigCPtr, this);
  }

  public String getMemberOfFamily() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getMemberOfFamily(swigCPtr, this);
  }

  public String getLogicalNumber() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getLogicalNumber(swigCPtr, this);
  }

  public String getChipNumber() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getChipNumber(swigCPtr, this);
  }

  public String getValidityBeginDate() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getValidityBeginDate(swigCPtr, this);
  }

  public String getValidityEndDate() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getValidityEndDate(swigCPtr, this);
  }

  public String getSpecialStatus() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getSpecialStatus(swigCPtr, this);
  }

  public String getHeight() {
    return beidlibJava_WrapperJNI.BEID_EId_getHeight(swigCPtr, this);
  }

  public String getDocumentNumber() {
    return beidlibJava_WrapperJNI.BEID_EId_getDocumentNumber(swigCPtr, this);
  }

  public String getTaxNo() {
    return beidlibJava_WrapperJNI.BEID_EId_getTaxNo(swigCPtr, this);
  }

  public String getSocialSecurityNo() {
    return beidlibJava_WrapperJNI.BEID_EId_getSocialSecurityNo(swigCPtr, this);
  }

  public String getHealthNo() {
    return beidlibJava_WrapperJNI.BEID_EId_getHealthNo(swigCPtr, this);
  }

  public String getIssuingEntity() {
    return beidlibJava_WrapperJNI.BEID_EId_getIssuingEntity(swigCPtr, this);
  }

  public String getLocalofRequest() throws BEID_Exception {
    return beidlibJava_WrapperJNI.BEID_EId_getLocalofRequest(swigCPtr, this);
  }

  public String getGivenNameFather() {
    return beidlibJava_WrapperJNI.BEID_EId_getGivenNameFather(swigCPtr, this);
  }

  public String getSurnameFather() {
    return beidlibJava_WrapperJNI.BEID_EId_getSurnameFather(swigCPtr, this);
  }

  public String getGivenNameMother() {
    return beidlibJava_WrapperJNI.BEID_EId_getGivenNameMother(swigCPtr, this);
  }

  public String getSurnameMother() {
    return beidlibJava_WrapperJNI.BEID_EId_getSurnameMother(swigCPtr, this);
  }

  public String getParents() {
    return beidlibJava_WrapperJNI.BEID_EId_getParents(swigCPtr, this);
  }

  public BEID_ByteArray getPhoto() throws BEID_Exception {
    return new BEID_ByteArray(beidlibJava_WrapperJNI.BEID_EId_getPhoto(swigCPtr, this), false);
  }

  public String getPersoData() {
    return beidlibJava_WrapperJNI.BEID_EId_getPersoData(swigCPtr, this);
  }

  public String getValidation() {
    return beidlibJava_WrapperJNI.BEID_EId_getValidation(swigCPtr, this);
  }

}
