/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.portugal.eid;

public final class PTEID_Param {
  public final static PTEID_Param PTEID_PARAM_GENERAL_INSTALLDIR = new PTEID_Param("PTEID_PARAM_GENERAL_INSTALLDIR");
  public final static PTEID_Param PTEID_PARAM_GENERAL_INSTALL_PRO_DIR = new PTEID_Param("PTEID_PARAM_GENERAL_INSTALL_PRO_DIR");
  public final static PTEID_Param PTEID_PARAM_GENERAL_INSTALL_SDK_DIR = new PTEID_Param("PTEID_PARAM_GENERAL_INSTALL_SDK_DIR");
  public final static PTEID_Param PTEID_PARAM_GENERAL_CACHEDIR = new PTEID_Param("PTEID_PARAM_GENERAL_CACHEDIR");
  public final static PTEID_Param PTEID_PARAM_GENERAL_LANGUAGE = new PTEID_Param("PTEID_PARAM_GENERAL_LANGUAGE");
  public final static PTEID_Param PTEID_PARAM_LOGGING_DIRNAME = new PTEID_Param("PTEID_PARAM_LOGGING_DIRNAME");
  public final static PTEID_Param PTEID_PARAM_LOGGING_PREFIX = new PTEID_Param("PTEID_PARAM_LOGGING_PREFIX");
  public final static PTEID_Param PTEID_PARAM_LOGGING_FILENUMBER = new PTEID_Param("PTEID_PARAM_LOGGING_FILENUMBER");
  public final static PTEID_Param PTEID_PARAM_LOGGING_FILESIZE = new PTEID_Param("PTEID_PARAM_LOGGING_FILESIZE");
  public final static PTEID_Param PTEID_PARAM_LOGGING_LEVEL = new PTEID_Param("PTEID_PARAM_LOGGING_LEVEL");
  public final static PTEID_Param PTEID_PARAM_LOGGING_GROUP = new PTEID_Param("PTEID_PARAM_LOGGING_GROUP");
  public final static PTEID_Param PTEID_PARAM_CRL_SERVDOWNLOADNR = new PTEID_Param("PTEID_PARAM_CRL_SERVDOWNLOADNR");
  public final static PTEID_Param PTEID_PARAM_CRL_TIMEOUT = new PTEID_Param("PTEID_PARAM_CRL_TIMEOUT");
  public final static PTEID_Param PTEID_PARAM_CRL_CACHEDIR = new PTEID_Param("PTEID_PARAM_CRL_CACHEDIR");
  public final static PTEID_Param PTEID_PARAM_CRL_CACHEFILE = new PTEID_Param("PTEID_PARAM_CRL_CACHEFILE");
  public final static PTEID_Param PTEID_PARAM_CRL_LOCKFILE = new PTEID_Param("PTEID_PARAM_CRL_LOCKFILE");
  public final static PTEID_Param PTEID_PARAM_CERTVALID_ALLOWTESTC = new PTEID_Param("PTEID_PARAM_CERTVALID_ALLOWTESTC");
  public final static PTEID_Param PTEID_PARAM_CERTVALID_CRL = new PTEID_Param("PTEID_PARAM_CERTVALID_CRL");
  public final static PTEID_Param PTEID_PARAM_CERTVALID_OCSP = new PTEID_Param("PTEID_PARAM_CERTVALID_OCSP");
  public final static PTEID_Param PTEID_PARAM_CERTCACHE_CACHEFILE = new PTEID_Param("PTEID_PARAM_CERTCACHE_CACHEFILE");
  public final static PTEID_Param PTEID_PARAM_CERTCACHE_LINENUMB = new PTEID_Param("PTEID_PARAM_CERTCACHE_LINENUMB");
  public final static PTEID_Param PTEID_PARAM_CERTCACHE_VALIDITY = new PTEID_Param("PTEID_PARAM_CERTCACHE_VALIDITY");
  public final static PTEID_Param PTEID_PARAM_CERTCACHE_WAITDELAY = new PTEID_Param("PTEID_PARAM_CERTCACHE_WAITDELAY");
  public final static PTEID_Param PTEID_PARAM_PROXY_HOST = new PTEID_Param("PTEID_PARAM_PROXY_HOST");
  public final static PTEID_Param PTEID_PARAM_PROXY_PORT = new PTEID_Param("PTEID_PARAM_PROXY_PORT");
  public final static PTEID_Param PTEID_PARAM_PROXY_PACFILE = new PTEID_Param("PTEID_PARAM_PROXY_PACFILE");
  public final static PTEID_Param PTEID_PARAM_SECURITY_SINGLESIGNON = new PTEID_Param("PTEID_PARAM_SECURITY_SINGLESIGNON");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_STARTWIN = new PTEID_Param("PTEID_PARAM_GUITOOL_STARTWIN");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_STARTMINI = new PTEID_Param("PTEID_PARAM_GUITOOL_STARTMINI");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_SHOWPIC = new PTEID_Param("PTEID_PARAM_GUITOOL_SHOWPIC");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_SHOWTBAR = new PTEID_Param("PTEID_PARAM_GUITOOL_SHOWTBAR");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_VIRTUALKBD = new PTEID_Param("PTEID_PARAM_GUITOOL_VIRTUALKBD");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_AUTOCARDREAD = new PTEID_Param("PTEID_PARAM_GUITOOL_AUTOCARDREAD");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_CARDREADNUMB = new PTEID_Param("PTEID_PARAM_GUITOOL_CARDREADNUMB");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_REGCERTIF = new PTEID_Param("PTEID_PARAM_GUITOOL_REGCERTIF");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_REMOVECERTIF = new PTEID_Param("PTEID_PARAM_GUITOOL_REMOVECERTIF");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_FILESAVE = new PTEID_Param("PTEID_PARAM_GUITOOL_FILESAVE");
  public final static PTEID_Param PTEID_PARAM_XSIGN_TSAURL = new PTEID_Param("PTEID_PARAM_XSIGN_TSAURL");
  public final static PTEID_Param PTEID_PARAM_XSIGN_ONLINE = new PTEID_Param("PTEID_PARAM_XSIGN_ONLINE");
  public final static PTEID_Param PTEID_PARAM_XSIGN_WORKINGDIR = new PTEID_Param("PTEID_PARAM_XSIGN_WORKINGDIR");
  public final static PTEID_Param PTEID_PARAM_XSIGN_TIMEOUT = new PTEID_Param("PTEID_PARAM_XSIGN_TIMEOUT");
  public final static PTEID_Param PTEID_PARAM_GUITOOL_SHOWNOTIFICATION = new PTEID_Param("PTEID_PARAM_GUITOOL_SHOWNOTIFICATION");
  public final static PTEID_Param PTEID_PARAM_PROXY_CONNECT_TIMEOUT = new PTEID_Param("PTEID_PARAM_PROXY_CONNECT_TIMEOUT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PTEID_Param swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PTEID_Param.class + " with value " + swigValue);
  }

  private PTEID_Param(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PTEID_Param(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PTEID_Param(String swigName, PTEID_Param swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PTEID_Param[] swigValues = { PTEID_PARAM_GENERAL_INSTALLDIR, PTEID_PARAM_GENERAL_INSTALL_PRO_DIR, PTEID_PARAM_GENERAL_INSTALL_SDK_DIR, PTEID_PARAM_GENERAL_CACHEDIR, PTEID_PARAM_GENERAL_LANGUAGE, PTEID_PARAM_LOGGING_DIRNAME, PTEID_PARAM_LOGGING_PREFIX, PTEID_PARAM_LOGGING_FILENUMBER, PTEID_PARAM_LOGGING_FILESIZE, PTEID_PARAM_LOGGING_LEVEL, PTEID_PARAM_LOGGING_GROUP, PTEID_PARAM_CRL_SERVDOWNLOADNR, PTEID_PARAM_CRL_TIMEOUT, PTEID_PARAM_CRL_CACHEDIR, PTEID_PARAM_CRL_CACHEFILE, PTEID_PARAM_CRL_LOCKFILE, PTEID_PARAM_CERTVALID_ALLOWTESTC, PTEID_PARAM_CERTVALID_CRL, PTEID_PARAM_CERTVALID_OCSP, PTEID_PARAM_CERTCACHE_CACHEFILE, PTEID_PARAM_CERTCACHE_LINENUMB, PTEID_PARAM_CERTCACHE_VALIDITY, PTEID_PARAM_CERTCACHE_WAITDELAY, PTEID_PARAM_PROXY_HOST, PTEID_PARAM_PROXY_PORT, PTEID_PARAM_PROXY_PACFILE, PTEID_PARAM_SECURITY_SINGLESIGNON, PTEID_PARAM_GUITOOL_STARTWIN, PTEID_PARAM_GUITOOL_STARTMINI, PTEID_PARAM_GUITOOL_SHOWPIC, PTEID_PARAM_GUITOOL_SHOWTBAR, PTEID_PARAM_GUITOOL_VIRTUALKBD, PTEID_PARAM_GUITOOL_AUTOCARDREAD, PTEID_PARAM_GUITOOL_CARDREADNUMB, PTEID_PARAM_GUITOOL_REGCERTIF, PTEID_PARAM_GUITOOL_REMOVECERTIF, PTEID_PARAM_GUITOOL_FILESAVE, PTEID_PARAM_XSIGN_TSAURL, PTEID_PARAM_XSIGN_ONLINE, PTEID_PARAM_XSIGN_WORKINGDIR, PTEID_PARAM_XSIGN_TIMEOUT, PTEID_PARAM_GUITOOL_SHOWNOTIFICATION, PTEID_PARAM_PROXY_CONNECT_TIMEOUT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

