/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.portugal.eid;

public class PTEID_Certificate extends PTEID_Crypto {
  private long swigCPtr;

  protected PTEID_Certificate(long cPtr, boolean cMemoryOwn) {
    super(pteidlibJava_WrapperJNI.SWIGPTEID_CertificateUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTEID_Certificate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pteidlibJava_WrapperJNI.delete_PTEID_Certificate(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getLabel() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getLabel(swigCPtr, this);
  }

  public long getID() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getID(swigCPtr, this);
  }

  public PTEID_CertifStatus getStatus() throws java.lang.Exception {
    return PTEID_CertifStatus.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_getStatus__SWIG_0(swigCPtr, this));
  }

  public PTEID_CertifStatus getStatus(PTEID_ValidationLevel crl, PTEID_ValidationLevel ocsp) throws java.lang.Exception {
    return PTEID_CertifStatus.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_getStatus__SWIG_1(swigCPtr, this, crl.swigValue(), ocsp.swigValue()));
  }

  public PTEID_CertifType getType() throws java.lang.Exception {
    return PTEID_CertifType.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_getType(swigCPtr, this));
  }

  public PTEID_ByteArray getCertData() throws java.lang.Exception {
    return new PTEID_ByteArray(pteidlibJava_WrapperJNI.PTEID_Certificate_getCertData(swigCPtr, this), false);
  }

  public void getFormattedData(PTEID_ByteArray data) {
    pteidlibJava_WrapperJNI.PTEID_Certificate_getFormattedData(swigCPtr, this, PTEID_ByteArray.getCPtr(data), data);
  }

  public String getSerialNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getSerialNumber(swigCPtr, this);
  }

  public String getOwnerName() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getOwnerName(swigCPtr, this);
  }

  public String getIssuerName() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getIssuerName(swigCPtr, this);
  }

  public String getValidityBegin() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getValidityBegin(swigCPtr, this);
  }

  public String getValidityEnd() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getValidityEnd(swigCPtr, this);
  }

  public long getKeyLength() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_getKeyLength(swigCPtr, this);
  }

  public boolean isRoot() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_isRoot(swigCPtr, this);
  }

  public boolean isTest() {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_isTest(swigCPtr, this);
  }

  public boolean isFromPTeidValidChain() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_isFromPTeidValidChain(swigCPtr, this);
  }

  public boolean isFromCard() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_isFromCard(swigCPtr, this);
  }

  public PTEID_Certificate getIssuer() throws java.lang.Exception {
    return new PTEID_Certificate(pteidlibJava_WrapperJNI.PTEID_Certificate_getIssuer(swigCPtr, this), false);
  }

  public long countChildren() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_Certificate_countChildren(swigCPtr, this);
  }

  public PTEID_Certificate getChildren(long ulIndex) throws java.lang.Exception {
    return new PTEID_Certificate(pteidlibJava_WrapperJNI.PTEID_Certificate_getChildren(swigCPtr, this, ulIndex), false);
  }

  public PTEID_Crl getCRL() throws java.lang.Exception {
    return new PTEID_Crl(pteidlibJava_WrapperJNI.PTEID_Certificate_getCRL(swigCPtr, this), false);
  }

  public PTEID_OcspResponse getOcspResponse() throws java.lang.Exception {
    return new PTEID_OcspResponse(pteidlibJava_WrapperJNI.PTEID_Certificate_getOcspResponse(swigCPtr, this), false);
  }

  public PTEID_CertifStatus verifyCRL(boolean forceDownload) throws java.lang.Exception {
    return PTEID_CertifStatus.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_verifyCRL__SWIG_0(swigCPtr, this, forceDownload));
  }

  public PTEID_CertifStatus verifyCRL() throws java.lang.Exception {
    return PTEID_CertifStatus.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_verifyCRL__SWIG_1(swigCPtr, this));
  }

  public PTEID_CertifStatus verifyOCSP() throws java.lang.Exception {
    return PTEID_CertifStatus.swigToEnum(pteidlibJava_WrapperJNI.PTEID_Certificate_verifyOCSP(swigCPtr, this));
  }

}
