/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.portugal.eid;

public class PTEID_CardVersionInfo extends PTEID_XMLDoc {
  private long swigCPtr;

  protected PTEID_CardVersionInfo(long cPtr, boolean cMemoryOwn) {
    super(pteidlibJava_WrapperJNI.SWIGPTEID_CardVersionInfoUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTEID_CardVersionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pteidlibJava_WrapperJNI.delete_PTEID_CardVersionInfo(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public String getSerialNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSerialNumber(swigCPtr, this);
  }

  public String getComponentCode() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getComponentCode(swigCPtr, this);
  }

  public String getOsNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getOsNumber(swigCPtr, this);
  }

  public String getOsVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getOsVersion(swigCPtr, this);
  }

  public String getSoftmaskNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSoftmaskNumber(swigCPtr, this);
  }

  public String getSoftmaskVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSoftmaskVersion(swigCPtr, this);
  }

  public String getAppletVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletVersion(swigCPtr, this);
  }

  public String getGlobalOsVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getGlobalOsVersion(swigCPtr, this);
  }

  public String getAppletInterfaceVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletInterfaceVersion(swigCPtr, this);
  }

  public String getPKCS1Support() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getPKCS1Support(swigCPtr, this);
  }

  public String getKeyExchangeVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getKeyExchangeVersion(swigCPtr, this);
  }

  public String getAppletLifeCycle() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletLifeCycle(swigCPtr, this);
  }

  public String getGraphicalPersonalisation() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getGraphicalPersonalisation(swigCPtr, this);
  }

  public String getElectricalPersonalisation() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getElectricalPersonalisation(swigCPtr, this);
  }

  public String getElectricalPersonalisationInterface() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getElectricalPersonalisationInterface(swigCPtr, this);
  }

  public PTEID_ByteArray getSignature() throws java.lang.Exception {
    return new PTEID_ByteArray(pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSignature(swigCPtr, this), false);
  }

}
