Belgium eID middleware SDK - Java API: be.belgium.eid.BEID_Certificate Class Reference
be.belgium.eid.BEID_Certificate Class Reference
Class that represent one certificate.
Public Member Functions
synchronized void delete ()
String getLabel () throws java.lang.Exception
Get the label of the certificate.
long getID () throws java.lang.Exception
Get the id of the certificate.
BEID_CertifStatus getStatus () throws java.lang.Exception
Get the status of the certificate using the default or configured validation level.
BEID_CertifStatus getStatus (BEID_ValidationLevel crl, BEID_ValidationLevel ocsp) throws java.lang.Exception
Get the status of the certificate.
BEID_CertifType getType () throws java.lang.Exception
Get the type of the certificate.
BEID_ByteArray getCertData () throws java.lang.Exception
Get the content of the certificate.
void getFormattedData (BEID_ByteArray data)
Get the content of the certificate without trailing zero.
String getSerialNumber () throws java.lang.Exception
Get the serial number of the certificate.
String getOwnerName () throws java.lang.Exception
Get the name of the owner of the certificate.
String getIssuerName () throws java.lang.Exception
Get the name of the issuer of the certificate.
String getValidityBegin () throws java.lang.Exception
Get the validity begin date of the certificate.
String getValidityEnd () throws java.lang.Exception
Get the validity end date of the certificate.
long getKeyLength () throws java.lang.Exception
Get the length of public/private key on the certificate.
boolean isRoot () throws java.lang.Exception
Check if this is a root certificate;.
boolean isTest ()
Check if this is a test certificate.
boolean isFromBeidValidChain () throws java.lang.Exception
Return true if the certificate chain ends by the beid root certificate.
boolean isFromCard () throws java.lang.Exception
Return true if this certificate comes from the card.
BEID_Certificate getIssuer () throws java.lang.Exception
Get the issuer of the certificate.
long countChildren () throws java.lang.Exception
Get the number of children of this certificate.
BEID_Certificate getChildren (long ulIndex) throws java.lang.Exception
Get a child certificate (certificate that has been issued by this one).
BEID_Crl getCRL () throws java.lang.Exception
Get the crl of the certificate;.
BEID_OcspResponse getOcspResponse () throws java.lang.Exception
Return the ocsp response object of the certificate;.
BEID_CertifStatus verifyCRL (boolean forceDownload) throws java.lang.Exception
Verify the certificate trough CRL validation.
BEID_CertifStatus verifyCRL () throws java.lang.Exception
Verify the certificate trough CRL validation (uses the CRL cache if possible).
BEID_CertifStatus verifyOCSP () throws java.lang.Exception
Verify the certificate trough OCSP validation.
Protected Member Functions
BEID_Certificate (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (BEID_Certificate obj)
Detailed Description
Class that represent one certificate.
Constructor & Destructor Documentation
be.belgium.eid.BEID_Certificate.BEID_Certificate (long cPtr, boolean cMemoryOwn) [protected]
Referenced by be.belgium.eid.BEID_Certificate.getChildren(), and be.belgium.eid.BEID_Certificate.getIssuer().
Member Function Documentation
long be.belgium.eid.BEID_Certificate.countChildren () throws java.lang.Exception
Get the number of children of this certificate.
synchronized void be.belgium.eid.BEID_Certificate.delete ()
Reimplemented from be.belgium.eid.BEID_Crypto.
References be.belgium.eid.BEID_Object.swigCMemOwn.
void be.belgium.eid.BEID_Certificate.finalize () [protected]
Reimplemented from be.belgium.eid.BEID_Crypto.
BEID_ByteArray be.belgium.eid.BEID_Certificate.getCertData () throws java.lang.Exception
Get the content of the certificate.
BEID_Certificate be.belgium.eid.BEID_Certificate.getChildren (long ulIndex) throws java.lang.Exception
Get a child certificate (certificate that has been issued by this one).
Parameters:
ulIndex is the child index (first child is 0). Throws BEID_ExParamRange exception if the index is out of range
References be.belgium.eid.BEID_Certificate.BEID_Certificate().
static long be.belgium.eid.BEID_Certificate.getCPtr (BEID_Certificate obj) [static, protected]
References be.belgium.eid.BEID_Certificate.swigCPtr.
BEID_Crl be.belgium.eid.BEID_Certificate.getCRL () throws java.lang.Exception
Get the crl of the certificate;.
void be.belgium.eid.BEID_Certificate.getFormattedData (BEID_ByteArray data)
Get the content of the certificate without trailing zero.
long be.belgium.eid.BEID_Certificate.getID () throws java.lang.Exception
Get the id of the certificate.
BEID_Certificate be.belgium.eid.BEID_Certificate.getIssuer () throws java.lang.Exception
Get the issuer of the certificate.
If there is no issuer (root), BEID_ExCertNoIssuer exception is thrown
References be.belgium.eid.BEID_Certificate.BEID_Certificate().
String be.belgium.eid.BEID_Certificate.getIssuerName () throws java.lang.Exception
Get the name of the issuer of the certificate.
long be.belgium.eid.BEID_Certificate.getKeyLength () throws java.lang.Exception
Get the length of public/private key on the certificate.
String be.belgium.eid.BEID_Certificate.getLabel () throws java.lang.Exception
Get the label of the certificate.
BEID_OcspResponse be.belgium.eid.BEID_Certificate.getOcspResponse () throws java.lang.Exception
Return the ocsp response object of the certificate;.
String be.belgium.eid.BEID_Certificate.getOwnerName () throws java.lang.Exception
Get the name of the owner of the certificate.
String be.belgium.eid.BEID_Certificate.getSerialNumber () throws java.lang.Exception
Get the serial number of the certificate.
BEID_CertifStatus be.belgium.eid.BEID_Certificate.getStatus (BEID_ValidationLevel crl, BEID_ValidationLevel ocsp) throws java.lang.Exception
Get the status of the certificate.
Parameters:
crl CRL validation level
See also:
BEID_ValidationLevel
Parameters:
ocsp OCSP validation level
See also:
BEID_ValidationLevel
References be.belgium.eid.BEID_CertifStatus.swigToEnum().
BEID_CertifStatus be.belgium.eid.BEID_Certificate.getStatus () throws java.lang.Exception
Get the status of the certificate using the default or configured validation level.
References be.belgium.eid.BEID_CertifStatus.swigToEnum().
BEID_CertifType be.belgium.eid.BEID_Certificate.getType () throws java.lang.Exception
Get the type of the certificate.
References be.belgium.eid.BEID_CertifType.swigToEnum().
String be.belgium.eid.BEID_Certificate.getValidityBegin () throws java.lang.Exception
Get the validity begin date of the certificate.
String be.belgium.eid.BEID_Certificate.getValidityEnd () throws java.lang.Exception
Get the validity end date of the certificate.
boolean be.belgium.eid.BEID_Certificate.isFromBeidValidChain () throws java.lang.Exception
Return true if the certificate chain ends by the beid root certificate.
boolean be.belgium.eid.BEID_Certificate.isFromCard () throws java.lang.Exception
Return true if this certificate comes from the card.
boolean be.belgium.eid.BEID_Certificate.isRoot () throws java.lang.Exception
Check if this is a root certificate;.
boolean be.belgium.eid.BEID_Certificate.isTest ()
Check if this is a test certificate.
Returns:
true if this is test certificate
BEID_CertifStatus be.belgium.eid.BEID_Certificate.verifyCRL () throws java.lang.Exception
Verify the certificate trough CRL validation (uses the CRL cache if possible).
References be.belgium.eid.BEID_CertifStatus.swigToEnum().
BEID_CertifStatus be.belgium.eid.BEID_Certificate.verifyCRL (boolean forceDownload) throws java.lang.Exception
Verify the certificate trough CRL validation.
Parameters:
forceDownload if true will force a new download of the CRL, otherwise use the CRL cache
References be.belgium.eid.BEID_CertifStatus.swigToEnum().
BEID_CertifStatus be.belgium.eid.BEID_Certificate.verifyOCSP () throws java.lang.Exception
Verify the certificate trough OCSP validation.
References be.belgium.eid.BEID_CertifStatus.swigToEnum().