/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

public enum PTEID_CertifType {
  PTEID_CERTIF_TYPE_UNKNOWN,
  PTEID_CERTIF_TYPE_ROOT,
  PTEID_CERTIF_TYPE_CA,
  PTEID_CERTIF_TYPE_AUTHENTICATION,
  PTEID_CERTIF_TYPE_SIGNATURE
}

}
