/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

public enum PTEID_DocumentType {
  PTEID_DOCTYPE_FULL = 0,
  PTEID_DOCTYPE_ID,
  PTEID_DOCTYPE_ADDRESS,
  PTEID_DOCTYPE_SOD,
  PTEID_DOCTYPE_INFO,
  PTEID_DOCTYPE_PINS,
  PTEID_DOCTYPE_CERTIFICATES
}

}
