/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.portugal.eid;

public class PTEID_RawData_Sis {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PTEID_RawData_Sis(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTEID_RawData_Sis obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pteidlibJava_WrapperJNI.delete_PTEID_RawData_Sis(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setIdData(PTEID_ByteArray value) {
    pteidlibJava_WrapperJNI.PTEID_RawData_Sis_idData_set(swigCPtr, this, PTEID_ByteArray.getCPtr(value), value);
  }

  public PTEID_ByteArray getIdData() {
    long cPtr = pteidlibJava_WrapperJNI.PTEID_RawData_Sis_idData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PTEID_ByteArray(cPtr, false);
  }

  public PTEID_RawData_Sis() {
    this(pteidlibJava_WrapperJNI.new_PTEID_RawData_Sis(), true);
  }

}
