/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package be.portugal.eid;

/******************************************************************************//**
  * Class for the info document.
  * \see PTEID_EIDCard.getVersionInfo() PTEID_EIDCard.getDocument()
  *********************************************************************************/
public class PTEID_CardVersionInfo extends PTEID_XMLDoc {
  private long swigCPtr;

  protected PTEID_CardVersionInfo(long cPtr, boolean cMemoryOwn) {
    super(pteidlibJava_WrapperJNI.SWIGPTEID_CardVersionInfoUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PTEID_CardVersionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      pteidlibJava_WrapperJNI.delete_PTEID_CardVersionInfo(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

	/** Get the serial number of the card */
  public String getSerialNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSerialNumber(swigCPtr, this);
  }

	/** Get the componenCode of the card  */
  public String getComponentCode() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getComponentCode(swigCPtr, this);
  }

	/** Get the OS number of the card */
  public String getOsNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getOsNumber(swigCPtr, this);
  }

	/** Get the OS version of the card */
  public String getOsVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getOsVersion(swigCPtr, this);
  }

	/** Get the softmask number of the card */
  public String getSoftmaskNumber() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSoftmaskNumber(swigCPtr, this);
  }

	/** Get the softmask version of the card */
  public String getSoftmaskVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSoftmaskVersion(swigCPtr, this);
  }

	/** Get the applet version of the card */
  public String getAppletVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletVersion(swigCPtr, this);
  }

	/** Get the global Os version of the card */
  public String getGlobalOsVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getGlobalOsVersion(swigCPtr, this);
  }

	/** Get the applet interface version of the card */
  public String getAppletInterfaceVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletInterfaceVersion(swigCPtr, this);
  }

	/** Get the PKCS#1 support of the card */
  public String getPKCS1Support() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getPKCS1Support(swigCPtr, this);
  }

	/** Get the key exchange version of the card */
  public String getKeyExchangeVersion() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getKeyExchangeVersion(swigCPtr, this);
  }

	/** Get the applet life cycle of the card */
  public String getAppletLifeCycle() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getAppletLifeCycle(swigCPtr, this);
  }

	/** Get field 'GraphicalPersonalisation' from the TokenInfo file */
  public String getGraphicalPersonalisation() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getGraphicalPersonalisation(swigCPtr, this);
  }

	/** Get field 'ElectricalPersonalisation' from the TokenInfo file */
  public String getElectricalPersonalisation() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getElectricalPersonalisation(swigCPtr, this);
  }

	/** Get field 'ElectricalPersonalisationInterface' from the TokenInfo file */
  public String getElectricalPersonalisationInterface() throws java.lang.Exception {
    return pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getElectricalPersonalisationInterface(swigCPtr, this);
  }

	/** Get the signature of the card info */
  public PTEID_ByteArray getSignature() throws java.lang.Exception {
    return new PTEID_ByteArray(pteidlibJava_WrapperJNI.PTEID_CardVersionInfo_getSignature(swigCPtr, this), false);
  }

}
