/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace be.portugal.eid {

public enum PTEID_CrlStatus {

    /// <summary>Validity unknown</summary>
    PTEID_CRL_STATUS_UNKNOWN,

    /// <summary>Valid Crl</summary>
    PTEID_CRL_STATUS_VALID,

    /// <summary>Connection problem</summary>
    PTEID_CRL_STATUS_CONNECT,

    /// <summary>Error during validation</summary>
    PTEID_CRL_STATUS_ERROR
}

}
